// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA876f7gNMmLnF-hzJAEEq7KoHIqsPl13w',
    appId: '1:524777499100:web:6b40985bd30b2288c54719',
    messagingSenderId: '524777499100',
    projectId: 'project-bd33c',
    authDomain: 'project-bd33c.firebaseapp.com',
    storageBucket: 'project-bd33c.firebasestorage.app',
    measurementId: 'G-J32XWT33FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-euvF5YDMoar8F03PZvALwXhSGKfDWo',
    appId: '1:524777499100:android:e658ec40191fae8dc54719',
    messagingSenderId: '524777499100',
    projectId: 'project-bd33c',
    storageBucket: 'project-bd33c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZysm4II_wAp9NVJrz3qTj98DRBXTvtU',
    appId: '1:524777499100:ios:dfc1d4ef2d6c733fc54719',
    messagingSenderId: '524777499100',
    projectId: 'project-bd33c',
    storageBucket: 'project-bd33c.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIZysm4II_wAp9NVJrz3qTj98DRBXTvtU',
    appId: '1:524777499100:ios:dfc1d4ef2d6c733fc54719',
    messagingSenderId: '524777499100',
    projectId: 'project-bd33c',
    storageBucket: 'project-bd33c.firebasestorage.app',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA876f7gNMmLnF-hzJAEEq7KoHIqsPl13w',
    appId: '1:524777499100:web:75d7588a84cfdd2ac54719',
    messagingSenderId: '524777499100',
    projectId: 'project-bd33c',
    authDomain: 'project-bd33c.firebaseapp.com',
    storageBucket: 'project-bd33c.firebasestorage.app',
    measurementId: 'G-HK0L6KB01R',
  );
}
